language: python
python: "3.4.2"
script: true
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
before_deploy:
 - openssl aes-256-cbc -K $encrypted_52b203b52387_key -iv $encrypted_52b203b52387_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/deploy_rsa
 - ssh-add /tmp/deploy_rsa
